---
title: "Workshop Data"
format: html
page-layout: full 
draft: false
---

## Location on OSCER

Sample FASTQ files for this workshop can be found on OSCER at:

`/ourdisk/hpc/iicomicswshp/dont_archive/omics_workshop_2025/mouse_kidney_all_cells_raw_data`

## Background

The single cell data used for class was generated from the kidneys of a mouse model of polycystic kidney disease. Specifically, the mice used for these experiments had a mutation in the Ift88 gene, which is required for primary cilia formation. In the absence of Ift88 and primary cilia, mice gradual develop cysts and fibrosis throughout the kidney parenchyma.

CaggcreERT2 Ift88f/f mice were induced with tamoxifen at 8 weeks of age, resulting in loss of primary cilia in the majority of cells in the kidney. Mice were harvested ~7 months post tamoxifen injection and kidneys isolated, digested with collagenase, Fluorescence-Activated Cell (FAC) sorted, and subjected to single cell RNA sequencing using 10X genomics. 

The manuscript associated with this data can be found here: [A Comprehensive Immune Cell Atlas of Cystic Kidney Disease Reveals the Involvement of Adaptive Immune Cells in Injury-Mediated Cyst Progression in Mice](https://pmc.ncbi.nlm.nih.gov/articles/PMC8970461/#sec5){target="_blank"}



