---
draft: true
---

# Why Single Cell RNA Sequencing?

You've heard of bulk RNA sequencing...but have you heard of single-cell RNA sequencing? I bet you have. All jokes aside, single-cell RNA sequencing technology has become the most effective and commonly used method for addressing the limitated data produced from bulk RNA sequencing. Although a similar concept to bulk (only difference is for each cell..every single cell some may say), single-cell RNA sequencing allows you to investigate the heterogeneity of cells coming from your sample and the variety of RNA transcripts from each cell. 

# Impact on Campus

The purpose of the Single Cell RNA Sequencing Workshop is to teach researchers on our campus how to perform single-cell RNA sequencing analysis from sample preparation to generation of publication-quality figures. 

In this hands-on workshop, participants will learn how to align sequencing data to the appropriate reference genomes, upload the data into R, and generate usable visualizations including UMAPs, Heatmaps, and Volcano plots. 

The course will also cover ligand-receptor interaction, pathway, and pseudotime analyses on the resulting data.

# Overview of Workshop

Our 2025 workshop will be split into three sessions spanning over a week. Sample prep, sequencing, and quality control methods will be covered in the first session. 

Using the newly generated data created in the first session, researchers will learn to import their data into R, create and manage a Seurat object, cell clustering methods, and cell annotation. 

Lastly, researchers will get hands-on experience with pseudotime analysis, cell-to-cell communication, and pathway/transcription factor inference methods.
