---
title: "Day 3"
subtitle: “Hang in there. We’re almost there.” — Free Willy (1993)
format: html
draft: false
---

### Before Session

:::{.callout-note collapse="true" appearance="simple"}
## Day 3 Pre-baked Material
### Locations
Data:
`/ourdisk/hpc/iicomicswshp/dont_archive/omics_workshop_2025/day3/data`

Scripts:
`/ourdisk/hpc/iicomicswshp/dont_archive/omics_workshop_2025/day3/scripts`

### SCP Reminder
Data:
`scp -r OSCER_USERNAME@sooner.oscer.ou.edu:'/ourdisk/hpc/iicomicswshp/dont_archive/omics_workshop_2025/day3/data' LOCAL_PATH`

Scripts:
`scp -r OSCER_USERNAME@sooner.oscer.ou.edu:'/ourdisk/hpc/iicomicswshp/dont_archive/omics_workshop_2025/day3/scripts' LOCAL_PATH`
:::

- [Pre-lecture Reading Link for Day 3](https://eleanacab.github.io/scRNAseq-wshp/pre-readings/day-3-pre-reading.html){target="_blank"} 


### Session Objectives

- Determining the root using Cytotrace
- Pseudotime analysis using Monocle3
- Cell-cell communication using CellChat
- Gene set enrichment analysis (GSEA) using clusterProfiler
- Pathway/transcription factor inference using decoupleR

### Session Materials

- [Morning Slides by Kurt Zimmerman and Hua Zhong](https://drive.google.com/file/d/1n4NICHo4WYVSc6OHHeNaunsmMspxqFJz/view?usp=drive_link){target="_blank"} 

- [Afternoon Slides by by Kurt Zimmerman and Hua Zhong](https://drive.google.com/file/d/1tjHAb6L592GHtmUvZ-zxgxY6jzqesDgT/view?usp=drive_link){target="_blank"}

### End of Workshop Feedback Form

Link: [Single Cell RNA-seq 2025 Workshop Feedback Form](https://forms.office.com/r/x2ApZC0yv2){target="_blank"}

