---
title: "Day 2"
subtitle: “Just keep swimming.” — Finding Nemo (2003)
format: html
draft: false
---

### Before Session

::: {.callout-note collapse="true" appearance="simple" }
## Day 2 Pre-baked Material Location
`/ourdisk/hpc/iicomicswshp/dont_archive/omics_workshop_2025/day2/data/`
:::

::: {.callout-note collapse="true" appearance="simple" }
## Day 2 Scripts Location
`/ourdisk/hpc/iicomicswshp/dont_archive/omics_workshop_2025/day2/scripts/`
:::

- [Pre-lecture Reading Link for Day 2](https://eleanacab.github.io/scRNAseq-wshp/pre-readings/day-2-pre-reading.html){target="_blank"}

### Session Objectives

- Understanding how the R package **Seurat** works as the core framework for:
  - Data quality checking and filtering
  - Integration across samples
  - Visualization
  - Clustering of cells
  - Annotating cell using a custom atlas
  - Sub-clustering of specific cell types

### Session Materials

- [Morning Slides by Lindsay Hayes](https://docs.google.com/presentation/d/17jriXrCrSdKn6YCFmbPQO4UUGWDzMg-VHuSGxR-66-k/edit?usp=sharing){target="_blank"} 

- [Afternoon Slides by Lindsay Hayes](https://docs.google.com/presentation/d/1cjqYfqHRptAFrraq4I_jIGLePeOstXh1F81fzwZQwyo/edit?usp=sharing){target="_blank"}

### Breakout Session Guides

- [Session 1](https://docs.google.com/document/d/1kPzDchmVi7ROHJLWOXApCf7xh1qGPXPI5z7vRzTPwww/edit?usp=sharing){target="_blank"} - Seurat Creation to Normalization
	
	- [Session 1 Answers](https://eleanacab.github.io/scRNAseq-wshp/days-content/day-2-answers/D2_B1_Hayes.nb.html){target="_blank"}

- [Session 2](https://docs.google.com/document/d/1WExtwoU3v3b2penO7sUYOaxJkwPCHA1gq_B4uT0RNSM/edit?usp=sharing){target="_blank"} - Dimension Reduction
	
	- [Session 2 Answers](https://eleanacab.github.io/scRNAseq-wshp/days-content/day-2-answers/D2_B2_Hayes.nb.html){target="_blank"}
	
- [Session 3](https://docs.google.com/document/d/1u6qHmQW7_dsIMXlMZ1F0wQ--kcAg3NSOKhOO6v07Y8s/edit?usp=sharing){target="_blank"} -  Integration
	
	- [Session 3 Answers](https://eleanacab.github.io/scRNAseq-wshp/days-content/day-2-answers/D2_B3_Hayes.nb.html){target="_blank"}
	
- [Session 4](https://docs.google.com/document/d/1f1PYwGLttjpfxC1ceyE2L8OrFcZv40U1MNqRSCEouIk/edit?usp=sharing){target="_blank"} -  Cluster Markers
	
	- [Session 4 Answers](https://eleanacab.github.io/scRNAseq-wshp/days-content/day-2-answers/D2_B4_Hayes.nb.html){target="_blank"}
	
- [Session 5](https://docs.google.com/document/d/1pIG6rxdfwbrLHMQFjDyJanzUCQ2RW0NWLsCRVz5e9wA/edit?usp=sharing){target="_blank"} -  Annotation
	
	- [Session 5 Answers](https://eleanacab.github.io/scRNAseq-wshp/days-content/day-2-answers/D2_B5_Hayes.nb.html){target="_blank"}
	
- [Session 6](https://docs.google.com/document/d/1alFb54RsiVlyetImB2cjvnAk_TmgbOYIXOM17kj6CMg/edit?usp=sharing){target="_blank"} -  Abundance
	
	- [Session 6 Answers](https://eleanacab.github.io/scRNAseq-wshp/days-content/day-2-answers/D2_B6_Hayes.nb.html){target="_blank"}
	
- [Session 7](https://docs.google.com/document/d/1mKHa4oqhX_I_dBE17OF8cGauiztGDnpPb8KQehbQ0BY/edit?usp=sharing){target="_blank"} -  Sub-Clustering
	
	- [Session 7 Answers](https://eleanacab.github.io/scRNAseq-wshp/days-content/day-2-answers/D2_B7_Hayes.nb.html){target="_blank"}